import type { Metadata } from 'next';
import { Roboto_Condensed } from 'next/font/google';
import { Cardo } from 'next/font/google';
import { Marcellus } from 'next/font/google';
import './globals.css';
import Navbar from '@/components/Navbar';
import Promo from '@/components/Promo';

// const inter = Inter({ subsets: ["latin"] });
const roboto_condensed = Roboto_Condensed({
    subsets: ['latin'],
    display: 'swap',
    variable: '--font-robcons',
});

const marcellus = Marcellus({
  weight: '400',
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-marcellus'
});

const cardo = Cardo({
    weight: '400',
    subsets: ['latin'],
    variable: '--font-cardo',
    display: 'swap',
});

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body className={`${roboto_condensed.className} ${cardo.variable} ${marcellus.variable}`}>
                <Promo />
                <div>
                    <Navbar />
                    {children}
                </div>
            </body>
        </html>
    );
}
